### ISSUE TITLE
TwitterAPIで特定の時間帯のつぶやきを取得してくる

### ISSUE THREAD

**Issue by UNE-fun** [UNE-fun/p2hacks_xmastree#3]
TeitterAPIの使用して、特定の時間帯のつぶやきを取得してくる。
色めき度合いに関しては #2 のタスクとする。

**Comment by i544c** [comment]
TwitterAPIを使ってツイートを取得する方法を調べた。
- [Search Tweets](https://developer.twitter.com/en/docs/tweets/search/overview)
  - 「クリスマス」の文字列が含まれるツイートを取得できる
  - 7日分だけ過去のツイートを遡って取得できる
- [Filter realtime Tweets](https://developer.twitter.com/en/docs/tweets/filter-realtime/overview)
  - 多分指定した文字列が含まれるツイートをstreamで取ってこれる

今のところリアムタイム性は考えていないので、とりあえずSearch Tweetsで実装してみる。
